$ErrorActionPreference = 'Stop'
$player = $null
$stream = $null
try {
    # Only the fixed PCM generated by main. No path, URL, volume or model arguments.
    $encoded = [Console]::In.ReadToEnd()
    if ($encoded.Length -ne 294060) { throw 'Invalid notification' }
    $wave = [Convert]::FromBase64String($encoded)
    if ($wave.Length -ne 220544 -or
        [Text.Encoding]::ASCII.GetString($wave, 0, 4) -ne 'RIFF' -or
        [BitConverter]::ToUInt32($wave, 4) -ne 220536 -or
        [Text.Encoding]::ASCII.GetString($wave, 8, 8) -ne 'WAVEfmt ' -or
        [BitConverter]::ToUInt32($wave, 16) -ne 16 -or
        [BitConverter]::ToUInt16($wave, 20) -ne 1 -or
        [BitConverter]::ToUInt16($wave, 22) -ne 1 -or
        [BitConverter]::ToUInt32($wave, 24) -ne 22050 -or
        [BitConverter]::ToUInt32($wave, 28) -ne 44100 -or
        [BitConverter]::ToUInt16($wave, 32) -ne 2 -or
        [BitConverter]::ToUInt16($wave, 34) -ne 16 -or
        [Text.Encoding]::ASCII.GetString($wave, 36, 4) -ne 'data' -or
        [BitConverter]::ToUInt32($wave, 40) -ne 220500) { throw 'Invalid notification' }
    $stream = [IO.MemoryStream]::new($wave, $false)
    $player = [System.Media.SoundPlayer]::new($stream)
    $player.Load()
    [Console]::Out.WriteLine('STAG_WAIT_SOUND_READY')
    $player.PlaySync()
    [Console]::Out.WriteLine('STAG_WAIT_SOUND_DONE')
} catch {
    [Console]::Error.WriteLine('STAG_WAIT_SOUND_FAILED')
    exit 1
} finally {
    if ($null -ne $player) { $player.Stop(); $player.Dispose() }
    if ($null -ne $stream) { $stream.Dispose() }
}
