import { nativeImage, type BrowserWindow } from "electron";
import type { Snapshot } from "../shared/types";

export const waitingTitle = "STAG — Aguardando sua resposta";

// Fixed pixels generated by the application; no text, paths or tool arguments in the badge.
export function attentionIcon() {
  const size = 16;
  const pixels = Buffer.alloc(size * size * 4);
  for (let y = 0; y < size; y++) {
    for (let x = 0; x < size; x++) {
      if ((x - 7.5) ** 2 + (y - 7.5) ** 2 > 56) continue;
      const mark = (x === 7 || x === 8) && ((y >= 3 && y <= 8) || y === 11 || y === 12);
      pixels.set(mark ? [255, 255, 255, 255] : [6, 119, 217, 255], (y * size + x) * 4);
    }
  }
  return nativeImage.createFromBitmap(pixels, { width: size, height: size, scaleFactor: 1 });
}

/** Presentation only: authoritative pending requests still belong to AssistantService. */
export class TaskbarAttention {
  private waiting = false;
  private flashing = false;
  private disposed = false;
  private readonly icon = attentionIcon();
  private readonly refresh = () => this.updateFlash();
  private readonly preserveTitle = (event: Electron.Event) => event.preventDefault();

  constructor(
    private readonly window: BrowserWindow,
    private readonly platform = process.platform,
  ) {
    window.on("focus", this.refresh);
    window.on("blur", this.refresh);
    window.on("minimize", this.refresh);
    window.on("hide", this.refresh);
    window.on("closed", this.dispose);
    window.on("page-title-updated", this.preserveTitle);
  }

  update(snapshot: Snapshot): void {
    if (this.disposed || this.window.isDestroyed()) return;
    const waiting =
      snapshot.connection === "ready" && !!snapshot.threadId && snapshot.approvals.length > 0;
    if (waiting !== this.waiting) {
      this.waiting = waiting;
      this.window.setTitle(waiting ? waitingTitle : "STAG");
      if (this.platform === "win32")
        this.window.setOverlayIcon(
          waiting ? this.icon : null,
          waiting ? "Aguardando sua resposta ou autorização" : "",
        );
    }
    this.updateFlash();
  }

  private updateFlash(): void {
    if (this.disposed || this.window.isDestroyed()) return;
    const flashing =
      this.waiting &&
      (!this.window.isFocused() || this.window.isMinimized() || !this.window.isVisible());
    if (flashing === this.flashing) return;
    this.flashing = flashing;
    this.window.flashFrame(flashing);
  }

  readonly dispose = (): void => {
    if (this.disposed) return;
    this.window.removeListener("focus", this.refresh);
    this.window.removeListener("blur", this.refresh);
    this.window.removeListener("minimize", this.refresh);
    this.window.removeListener("hide", this.refresh);
    this.window.removeListener("closed", this.dispose);
    this.window.removeListener("page-title-updated", this.preserveTitle);
    if (!this.window.isDestroyed()) {
      this.window.flashFrame(false);
      this.window.setTitle("STAG");
      if (this.platform === "win32") this.window.setOverlayIcon(null, "");
    }
    this.waiting = false;
    this.flashing = false;
    this.disposed = true;
  };
}
