import { nativeImage, type BrowserWindow } from "electron";
import type { EventEmitter } from "node:events";
import type { Snapshot } from "../shared/types";
import type { AttentionSound } from "./waiting-sound";
import { build } from "../../package.json";

export const waitingTitle = `${build.productName} — Aguardando sua resposta`;

// Fixed pixels generated by the application; no text, paths or tool arguments in the badge.
export function attentionIcon() {
  const size = 16;
  const pixels = Buffer.alloc(size * size * 4);
  for (let y = 0; y < size; y++) {
    for (let x = 0; x < size; x++) {
      if ((x - 7.5) ** 2 + (y - 7.5) ** 2 > 56) continue;
      const mark = (x === 7 || x === 8) && ((y >= 3 && y <= 8) || y === 11 || y === 12);
      pixels.set(mark ? [255, 255, 255, 255] : [6, 119, 217, 255], (y * size + x) * 4);
    }
  }
  return nativeImage.createFromBitmap(pixels, { width: size, height: size, scaleFactor: 1 });
}

/** Presentation only: authoritative pending requests still belong to AssistantService. */
export class TaskbarAttention {
  private waiting = false;
  private waitingThread: string | null = null;
  private flashing = false;
  private disposed = false;
  private thread: string | null = null;
  private working = false;
  private unbind: (() => void) | null = null;
  private readonly icon = attentionIcon();
  private readonly refresh = () => {
    if (this.window.isFocused() && !this.window.isMinimized() && this.window.isVisible())
      this.sound?.stop();
    this.updateFlash();
  };
  private readonly preserveTitle = (event: Electron.Event) => event.preventDefault();

  constructor(
    private readonly window: BrowserWindow,
    private readonly platform = process.platform,
    private readonly sound?: AttentionSound,
  ) {
    window.on("focus", this.refresh);
    window.on("blur", this.refresh);
    window.on("minimize", this.refresh);
    window.on("hide", this.refresh);
    window.on("closed", this.dispose);
    window.on("page-title-updated", this.preserveTitle);
  }

  update(snapshot: Snapshot): void {
    if (this.disposed || this.window.isDestroyed()) return;
    const waiting =
      snapshot.connection === "ready" && !!snapshot.threadId && snapshot.approvals.length > 0;
    const waitingThread = waiting ? snapshot.threadId : null;
    const thread = snapshot.connection === "ready" ? snapshot.threadId : null;
    const working =
      snapshot.busy ||
      !!snapshot.videoAnalysis?.working ||
      (!snapshot.queuePaused && snapshot.queuedMessages.length > 0);
    if (
      waitingThread !== this.waitingThread ||
      thread !== this.thread ||
      (working && !this.working)
    )
      this.sound?.stop();
    this.thread = thread;
    this.working = working;
    if (waitingThread !== this.waitingThread) {
      this.waitingThread = waitingThread;
      if (waiting && this.platform === "win32") this.sound?.play();
    }
    if (waiting !== this.waiting) {
      this.waiting = waiting;
      this.window.setTitle(waiting ? waitingTitle : build.productName);
      if (this.platform === "win32")
        this.window.setOverlayIcon(
          waiting ? this.icon : null,
          waiting ? "Aguardando sua resposta ou autorização" : "",
        );
    }
    this.updateFlash();
  }

  bind(source: EventEmitter): void {
    this.unbind?.();
    if (this.disposed) return;
    const update = (snapshot: Snapshot) => this.update(snapshot);
    const completed = ({ threadId }: { threadId: string }) => this.completed(threadId);
    const stopped = () => this.stopSound();
    source.on("snapshot", update);
    source.on("workCompleted", completed);
    source.on("workStopped", stopped);
    this.unbind = () => {
      source.removeListener("snapshot", update);
      source.removeListener("workCompleted", completed);
      source.removeListener("workStopped", stopped);
      this.unbind = null;
    };
  }

  completed(threadId: string): void {
    if (
      this.disposed ||
      this.window.isDestroyed() ||
      this.platform !== "win32" ||
      this.thread !== threadId ||
      this.waiting ||
      this.working
    )
      return;
    this.sound?.play();
  }

  stopSound(): void {
    this.sound?.stop();
  }

  private updateFlash(): void {
    if (this.disposed || this.window.isDestroyed()) return;
    const flashing =
      this.waiting &&
      (!this.window.isFocused() || this.window.isMinimized() || !this.window.isVisible());
    if (flashing === this.flashing) return;
    this.flashing = flashing;
    this.window.flashFrame(flashing);
  }

  readonly dispose = (): void => {
    if (this.disposed) return;
    this.unbind?.();
    this.window.removeListener("focus", this.refresh);
    this.window.removeListener("blur", this.refresh);
    this.window.removeListener("minimize", this.refresh);
    this.window.removeListener("hide", this.refresh);
    this.window.removeListener("closed", this.dispose);
    this.window.removeListener("page-title-updated", this.preserveTitle);
    this.sound?.stop();
    if (!this.window.isDestroyed()) {
      this.window.flashFrame(false);
      this.window.setTitle(build.productName);
      if (this.platform === "win32") this.window.setOverlayIcon(null, "");
    }
    this.waiting = false;
    this.waitingThread = null;
    this.thread = null;
    this.working = false;
    this.flashing = false;
    this.disposed = true;
  };

  settled(): Promise<void> {
    return this.sound?.settled() || Promise.resolve();
  }
}
